version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: geek_crawl-app
    restart: always
    working_dir: /var/www/
    tty: true
    volumes:
      - ./php:/var/www/php
      - ./dist:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: geekcrawl-nginx
    tty: true
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/php
      - ./dist:/var/www
      - ./nginx:/etc/nginx/conf.d