version: "3.9"
services:
  www:
    image: httpd
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./dist/:/usr/local/apache2/htdocs/
      - ./php/:/usr/local/apache2/htdocs/